package ebpfnew

const (
	FS = "/sys/fs/bpf"
)

const (
	BPF_PROG_SYSCALL_ENTER_READ   = "sys_enter_read"
	BPF_PROG_SYSCALL_EXIT_READ    = "sys_exit_read"
	BPF_PROG_SYSCALL_ENTER_OPENAT = "sys_enter_openat"
	BPF_PROG_SYSCALL_EXIT_OPENAT  = "sys_exit_openat"
)

const (
	BPF_MAPS_PAYLOAD_BUFFER = "map_payload_buffer"
)

const (
	BPF_PROG_FS_SYSCALL_ENTER_READ   = FS + "/" + BPF_PROG_SYSCALL_ENTER_READ
	BPF_PROG_FS_SYSCALL_EXIT_READ    = FS + "/" + BPF_PROG_SYSCALL_EXIT_READ
	BPF_PROG_FS_SYSCALL_ENTER_OPENAT = FS + "/" + BPF_PROG_SYSCALL_ENTER_OPENAT
	BPF_PROG_FS_SYSCALL_EXIT_OPENAT  = FS + "/" + BPF_PROG_SYSCALL_EXIT_OPENAT
)
